name: Build and Release

on:
  push:
    branches: [main]
  pull_request:

env:
  ARTIFACT_NAME: build-artifact

jobs:
  setup_release:
    name: Setup release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      mod_name: ${{ steps.get_mod_name.outputs.mod_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get C# project file
        id: get_project_file
        run: echo "csproj=$(find . -iname *.csproj | head -1)" >> $GITHUB_OUTPUT  

      - name: Get mod name
        id: get_mod_name
        run: |
          tag=AssemblyName
          mod_name=$(grep --only-matching --perl-regexp "<$tag>\K.*(?=</$tag>)" ${{ steps.get_project_file.outputs.csproj }})
          echo "mod_name=$mod_name" >> $GITHUB_OUTPUT 

      - name: Get assembly version
        id: get_version
        run: |
          tag=Version
          version=$(grep --only-matching --perl-regexp "<$tag>\K.*(?=</$tag>)" ${{ steps.get_project_file.outputs.csproj }})
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get recent Change Log
        id: get_changelog
        run: |
          query_regex="^## \[[0-9]*\.[0-9]*\.[0-9]*\] - [0-9]{4}-[0-9]{2}-[0-9]{2}$"
          cmd_output=$(grep --only-matching --perl-regexp "$query_regex" ChangeLog.md)
          echo "$(echo "$cmd_output" | head -2)" > temp.txt
          start=$(cat temp.txt | head -1 | sed --expression 's/[]\/$*.^[]/\\&/g')
          end=$(cat temp.txt | tail -1 | sed --expression 's/[]\/$*.^[]/\\&/g')
          body=$(awk "/$start/,/$end/ { print }" ChangeLog.md | head -n -1)
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_changelog.outputs.body }}
          draft: false
          prerelease: false

      - name: Get references
        run: |
          wget ${{ secrets.REFERENCES_LINK }} -O References.zip
          unzip References.zip -d References

      - name: Get macOS BepInEx
        run: |
          DOWNLOAD_URL=$(curl --request GET https://api.github.com/repos/BepInEx/BepInEx/releases/latest | jq -r '.assets[] | select(.name | contains("macos_x64")) | .browser_download_url')
          wget $DOWNLOAD_URL -O BepInEx_macOS.zip
          unzip BepInEx_macOS.zip -d BepInEx_macOS

      - name: Get Windows BepInEx
        run: |
          DOWNLOAD_URL=$(curl --request GET https://api.github.com/repos/BepInEx/BepInEx/releases/latest | jq -r '.assets[] | select(.name | contains("win_x64")) | .browser_download_url')
          wget $DOWNLOAD_URL -O BepInEx_Windows.zip
          unzip BepInEx_Windows.zip -d BepInEx_Windows
      
      - name: Upload references artifact
        uses: actions/upload-artifact@v4
        with:
          name: References
          path: References

      - name: Upload macOS BepInEx artifact
        uses: actions/upload-artifact@v4
        with:
          name: BepInEx_macOS
          path: BepInEx_macOS

      - name: Upload Windows BepInEx artifact
        uses: actions/upload-artifact@v4
        with:
          name: BepInEx_Windows
          path: BepInEx_Windows
  build_and_publish_macos:
    name: Build and Publish (macOS)
    needs: setup_release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download references artifact
        uses: actions/download-artifact@v4
        with:
          name: References

      - name: Download BepInEx artifact
        uses: actions/download-artifact@v4
        with:
          name: BepInEx_macOS
          path: BepInEx

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Restore packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Package with BepInEx
        id: package
        run: |
          cd BepInEx
          ZIP_FILE=${{ needs.setup_release.outputs.mod_name }}_macOS.zip
          zip -r $ZIP_FILE *
          echo "zipfile=BepInEx/$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup_release.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.zipfile }}
          asset_name: ${{ steps.package.outputs.zipfile }}
          asset_content_type: application/zip
  build_and_publish_windows:
    name: Build and Publish (Windows)
    needs: setup_release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download references artifact
        uses: actions/download-artifact@v4
        with:
          name: References

      - name: Download BepInEx artifact
        uses: actions/download-artifact@v4
        with:
          name: BepInEx_Windows
          path: BepInEx

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Restore packages
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Package with BepInEx
        id: package
        run: |
          $ZIP_FILE="${{ needs.setup_release.outputs.mod_name }}_Windows.zip"
          tar -acf $ZIP_FILE -C BepInEx *
          echo "ZIP FILE???? $ZIP_FILE"
          dir
          echo "zipfile=./$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup_release.outputs.upload_url }}
          asset_path: ${{ steps.package.outputs.zipfile }}
          asset_name: ${{ steps.package.outputs.zipfile }}
          asset_content_type: application/zip
